#
# %W% %E%
#
# Copyright (c) 1998 Sun Microsystems, Inc. All Rights Reserved.
#
# See also the LICENSE file in this distribution.
#
# Makefile for the example demonstrating shared dispatchers with JNI.
#

CLASSES    = ObjectArrayTest.class
OBJS       = ObjectArrayTest.o
MAIN_CLASS = ObjectArrayTest
NATIVE_LIB = libObjectArrayTest.so

include ../../makeincludes.mac

ObjectArrayTest.c : ObjectArrayTest.h
