
SUBDIRS = chap2 chap3 chap4 chap5 chap6 chap7 chap8 chap9

default: $(SUBDIRS)

$(SUBDIRS) ::
	@echo +++Recursively making $(ACTION) $@ ...
	@cd $@
	$(MAKE) -f makefile.win32 -nologo $(ACTION) 
	@cd ..
	@echo ---Finished Recursively making $(ACTION) $@.

clean:
	@$(MAKE) -f makefile.win32 -nologo ACTION=$@ 
