#
# %W% %E%
#
# Copyright (c) 1998 Sun Microsystems, Inc. All Rights Reserved.
#
# See also the LICENSE file in this distribution.
#
# NMake makefile for the example demonstrating shared dispatchers with
# JNI.
#

CLASSES    = Prog.class
OBJS       = attach.obj
NATIVE_APP = attach.exe

default: runapp

!include ..\..\makeincludes.win32
