#
# %W% %E%
#
# Copyright (c) 1998 Sun Microsystems, Inc. All Rights Reserved.
#
# See also the LICENSE file in this distribution.
#
# Makefile for the example demonstrating shared dispatchers with JNI.
#

CLASSES    = ThrowByName.class
OBJS       = ThrowByName.o
MAIN_CLASS = ThrowByName
NATIVE_LIB = libThrowByName.so

include ../../makeincludes.mac

ThrowByName.c : ThrowByName.h
