#
# %W% %E%
#
# Copyright (c) 1998 Sun Microsystems, Inc. All Rights Reserved.
#
# See also the LICENSE file in this distribution.
#
# NMake makefile for the example demonstrating shared dispatchers with
# JNI.
#

CLASSES    = StaticFieldAccess.class
OBJS       = StaticFieldAccess.obj
MAIN_CLASS = StaticFieldAccess
NATIVE_LIB = StaticFieldAccess.dll

!include ..\..\makeincludes.win32

StaticFieldAccess.c : StaticFieldAccess.h
