#
# %W% %E%
#
# Copyright (c) 1998 Sun Microsystems, Inc. All Rights Reserved.
#
# See also the LICENSE file in this distribution.
#
# Makefile for the example demonstrating shared dispatchers with JNI.
#

CLASSES    = CatchThrow.class
OBJS       = CatchThrow.o
MAIN_CLASS = CatchThrow
NATIVE_LIB = libCatchThrow.so

include ../../makeincludes.solaris

CatchThrow.c : CatchThrow.h
