#
# %W% %E%
#
# Copyright (c) 1998 Sun Microsystems, Inc. All Rights Reserved.
#
# See also the LICENSE file in this distribution.
#
# Makefile for the example demonstrating shared dispatchers with JNI.
#

CLASSES    = MyNewString.class
OBJS       = MyNewString.o
MAIN_CLASS = MyNewString
NATIVE_LIB = libMyNewString.so

include ../../makeincludes.solaris

MyNewString.c : MyNewString.h
