#
# %W% %E%
#
# Copyright (c) 1998 Sun Microsystems, Inc. All Rights Reserved.
#
# See also the LICENSE file in this distribution.
#
# NMake makefile for the example demonstrating shared dispatchers with
# JNI.
#

CLASSES    = IntArray.class
OBJS       = IntArray.obj
MAIN_CLASS = IntArray
NATIVE_LIB = IntArray.dll

!include ..\..\makeincludes.win32

IntArray.c : IntArray.h
