#
# %W% %E%
#
# Copyright (c) 1998 Sun Microsystems, Inc. All Rights Reserved.
#
# See also the LICENSE file in this distribution.
#
# Makefile for the example demonstrating shared dispatchers with JNI.
#

CLASSES    = HelloWorld.class
OBJS       = HelloWorld.o
MAIN_CLASS = HelloWorld
NATIVE_LIB = libHelloWorld.so

include ../../makeincludes.solaris

HelloWorld.c : HelloWorld.h
